name: "Build"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]
jobs:
  linux-build-local:
    name: Build ${{ matrix.java }} - Local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: mvn -s .github/mvn-settings.xml clean install -DskipTests